# Pruebas con pandas

Pruebas con la libreria de pandas

In [4]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame

### Series

In [3]:
s1 = Series(range(10,16))
s1

0    10
1    11
2    12
3    13
4    14
5    15
dtype: int64

In [5]:
s2 = Series(np.arange(6))
s2

0    0
1    1
2    2
3    3
4    4
5    5
dtype: int32

In [6]:
s3 = Series([1,2,3,4,5], index=list('adios'))
s3

a    1
d    2
i    3
o    4
s    5
dtype: int64

In [7]:
s3[0], s3['a']

(1, 1)

In [8]:
s4 = Series([1,2,3,4], index=list('hola'))
s4

h    1
o    2
l    3
a    4
dtype: int64

In [9]:
s3 + s4

a    5.0
d    NaN
h    NaN
i    NaN
l    NaN
o    6.0
s    NaN
dtype: float64

In [11]:
s3[s3 > 2]

i    3
o    4
s    5
dtype: int64

In [13]:
r = s3.add(s4, fill_value=0)
r

a    5.0
d    2.0
h    1.0
i    3.0
l    3.0
o    6.0
s    5.0
dtype: float64

In [14]:
print(r['a'])
print(r[['a','i','o']])
print(r[1:4])
print(r['a':'i'])

5.0
a    5.0
i    3.0
o    6.0
dtype: float64
d    2.0
h    1.0
i    3.0
dtype: float64
a    5.0
d    2.0
h    1.0
i    3.0
dtype: float64


In [15]:
r2 = r
r['a'] = 1000
print(r)
print(r2)


a    1000.0
d       2.0
h       1.0
i       3.0
l       3.0
o       6.0
s       5.0
dtype: float64
a    1000.0
d       2.0
h       1.0
i       3.0
l       3.0
o       6.0
s       5.0
dtype: float64


In [16]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr2 = arr[[0,3,5]]
arr2

array([0, 3, 5])

In [21]:
r = Series([1,2,3,4], index=list('hola'))
r3 = r.copy()
r['a'] = 1000
print(r, id(r))
print(r3, id(r3))

h       1
o       2
l       3
a    1000
dtype: int64 2485086506576
h    1
o    2
l    3
a    4
dtype: int64 2485086507984


In [22]:
s3

a    1
d    2
i    3
o    4
s    5
dtype: int64

In [23]:
s3[(s3 >= 2) & (s3 <= 4)]

d    2
i    3
o    4
dtype: int64

In [24]:
s3[(s3 >= 2)] = 2
s3

a    1
d    2
i    2
o    2
s    2
dtype: int64

In [25]:
np.exp(s3)

a    2.718282
d    7.389056
i    7.389056
o    7.389056
s    7.389056
dtype: float64

In [26]:
s3

a    1
d    2
i    2
o    2
s    2
dtype: int64

In [27]:
s3.isnull()

a    False
d    False
i    False
o    False
s    False
dtype: bool

In [28]:
pd.isnull(s3)

a    False
d    False
i    False
o    False
s    False
dtype: bool

### DataFrames

In [29]:
# Con un diccionario: clave => col, valores: list 
d = {k:np.random.randint(10,20,15)  for k in 'adios'}
d

{'a': array([14, 19, 17, 16, 19, 15, 13, 10, 14, 14, 15, 11, 11, 18, 18]),
 'd': array([11, 10, 13, 12, 11, 16, 16, 10, 18, 11, 13, 14, 16, 13, 11]),
 'i': array([17, 10, 12, 17, 10, 10, 10, 14, 16, 16, 15, 15, 14, 10, 12]),
 'o': array([14, 11, 11, 12, 18, 13, 11, 16, 12, 15, 10, 10, 12, 15, 16]),
 's': array([15, 12, 13, 18, 13, 16, 17, 19, 19, 11, 19, 16, 17, 13, 11])}

In [30]:
df = DataFrame(d)
df

a   d   i   o   s
0   14  11  17  14  15
1   19  10  10  11  12
2   17  13  12  11  13
3   16  12  17  12  18
4   19  11  10  18  13
5   15  16  10  13  16
6   13  16  10  11  17
7   10  10  14  16  19
8   14  18  16  12  19
9   14  11  16  15  11
10  15  13  15  10  19
11  11  14  15  10  16
12  11  16  14  12  17
13  18  13  10  15  13
14  18  11  12  16  11

In [31]:
m = np.arange(30).reshape(5,6)
df2 = DataFrame(m)
df2

0   1   2   3   4   5
0   0   1   2   3   4   5
1   6   7   8   9  10  11
2  12  13  14  15  16  17
3  18  19  20  21  22  23
4  24  25  26  27  28  29

In [35]:
df2.values

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [37]:
df2.values.tolist()

[[0, 1, 2, 3, 4, 5],
 [6, 7, 8, 9, 10, 11],
 [12, 13, 14, 15, 16, 17],
 [18, 19, 20, 21, 22, 23],
 [24, 25, 26, 27, 28, 29]]

In [38]:
# Una col:
df['a']

0     14
1     19
2     17
3     16
4     19
5     15
6     13
7     10
8     14
9     14
10    15
11    11
12    11
13    18
14    18
Name: a, dtype: int32

In [39]:
# Varias cols -> dataframe
df[['a','i','o']]

a   i   o
0   14  17  14
1   19  10  11
2   17  12  11
3   16  17  12
4   19  10  18
5   15  10  13
6   13  10  11
7   10  14  16
8   14  16  12
9   14  16  15
10  15  15  10
11  11  15  10
12  11  14  12
13  18  10  15
14  18  12  16

In [41]:
# Fila
df.loc[0]

a    14
d    11
i    17
o    14
s    15
Name: 0, dtype: int32

In [42]:
# Celda:
print(df['a'][0])
print(df.loc[0]['a'])


14
14


In [43]:
df.loc[:5]

a   d   i   o   s
0  14  11  17  14  15
1  19  10  10  11  12
2  17  13  12  11  13
3  16  12  17  12  18
4  19  11  10  18  13
5  15  16  10  13  16